name: Publish

on:
  release:
    types: [ created ]

permissions: {}

jobs:
  run:
    name: "Build and publish release"
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # for trusted publishing
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0
        with:
          version: "0.8.10"

      - run: uv python install 3.12
      - run: uv build
      - run: uv publish
